on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Publish code
        run: deno publish
